const db = require("./db");
async function uploadSR() {

  let SR = [
    { stationid: 1, routeid: 1 },
    { stationid: 1, routeid: 2 },
    { stationid: 2, routeid: 1 },
    { stationid: 2, routeid: 2 },
    { stationid: 2, routeid: 4 },
    { stationid: 2, routeid: 3 },
    { stationid: 2, routeid: 4 },
    { stationid: 3, routeid: 3 },
    { stationid: 3, routeid: 4 },
    { stationid: 3, routeid: 5 },
    { stationid: 3, routeid: 6 },
    { stationid: 3, routeid: 7 },
    { stationid: 3, routeid: 8},
    { stationid: 4, routeid: 5 },
    { stationid: 4, routeid: 6 },
    { stationid: 4, routeid: 9},
    { stationid: 4, routeid: 10 },
    { stationid: 5, routeid: 9 },
    { stationid: 5, routeid: 10 },
    { stationid: 6, routeid: 7 },
    { stationid: 6, routeid: 8 },
    { stationid: 6, routeid: 11 },
    { stationid: 6, routeid: 12 },
    { stationid: 7, routeid: 11 },
    { stationid: 7, routeid: 12 },
  ];
  for (let i = 0; i < SR.length; i++) {
    const element =SR[i];
    await db("se_project.stationroutes").insert(element).returning("*");
  }

}
async function uploadS() {
  let stations = [
    {
      stationname: "s1",
      stationtype: "normal",
      stationposition: "start",
      stationstatus: "old",
    },
    {
      stationname: "s2",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "s3",
      stationtype: "transfer",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "s4",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "s5",
      stationtype: "normal",
      stationposition: "end",
      stationstatus: "old",
    },
    {
      stationname: "s6",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "s7",
      stationtype: "normal",
      stationposition: "end",
      stationstatus: "old",
    },
  ];

  for (let i = 0; i < stations.length; i++) {
    const element =stations[i];
    await db("se_project.stations").insert(element).returning("*");
  }
}
async function uploadR() {
    let routes = [
      { routename: "hi12", fromstationid: 1, tostationid: 2 },
      { routename: "hi21", fromstationid: 2, tostationid: 1 },
      { routename: "hi23", fromstationid: 2, tostationid: 3 },
      { routename: "hi32", fromstationid: 3, tostationid: 2 },
      { routename: "hi34", fromstationid: 3, tostationid: 4 },
      { routename: "hi43", fromstationid: 4, tostationid: 3 },
      { routename: "hi36", fromstationid: 3, tostationid: 6 },
      { routename: "hi63", fromstationid: 6, tostationid: 3 },
      { routename: "hi45", fromstationid: 4, tostationid: 5 },
      { routename: "hi54", fromstationid: 5, tostationid: 4 },
      { routename: "hi76", fromstationid: 7, tostationid: 6 },
      { routename: "hi67", fromstationid: 6, tostationid: 7 },
    ];
  
  for (let i = 0; i < routes.length; i++) {
    const element =routes[i];
    await db("se_project.routes").insert(element).returning("*");
  }
}

async function uploadR1() {
  let routes = [
    { routename: "adly mansour - haykestep", fromstationid: 43, tostationid: 44 },
    { routename: "haykestep - adly mansour", fromstationid: 44, tostationid: 43 },
    { routename: "haykestep - omar ibn el khattab", fromstationid: 44, tostationid: 45 },
    { routename: "omar ibn el khattab - haykestep", fromstationid: 45, tostationid: 44},
    { routename: "omar ibn el khattab - qubaa", fromstationid: 45, tostationid: 46 },
    { routename: "qubaa - omar ibn el khattab", fromstationid: 46, tostationid: 45 },
    { routename: "qubaa - hesham barakat", fromstationid: 46, tostationid: 47 },
    { routename: "hesham barakat - qubaa", fromstationid: 47, tostationid: 46 },
    { routename: "hesham barakat - el nozha", fromstationid: 47, tostationid: 48},
    { routename: "el nozha - hesham barakat", fromstationid: 48, tostationid: 47},
    { routename: "el nozha - el shams club", fromstationid: 48, tostationid: 49},
    { routename: "el shams club - el nozha", fromstationid: 49, tostationid: 48},
    { routename: "el shams club - alf maskan", fromstationid: 49, tostationid: 50 },
    { routename: "alf maskan - el shams club", fromstationid: 50, tostationid: 49 },
    { routename: "alf maskan - helioples", fromstationid: 50, tostationid: 51 },
    { routename: "helioples - alf maskan", fromstationid: 51, tostationid: 50 },
    { routename: "helioples - haroun", fromstationid: 51, tostationid: 52 },
    { routename: "haroun - helioples", fromstationid: 52, tostationid: 51 },
    { routename: "haroun - al-ahram", fromstationid: 52, tostationid: 53 },
    { routename: "al-ahram - haroun", fromstationid: 53, tostationid: 52 },
    { routename: "al-ahram - koleyet el-banat", fromstationid: 53, tostationid: 54 },
    { routename: "koleyet el-banat - al-ahram", fromstationid: 54, tostationid: 53 },
    { routename: "koleyet el-banat - stadium", fromstationid: 54, tostationid: 55},
    { routename: "stadium - koleyet el-banat", fromstationid: 55, tostationid: 54 },
    { routename: "stadium - fair zone", fromstationid: 55, tostationid: 56 },
    { routename: "fair zone - stadium", fromstationid: 56, tostationid: 55 },
    { routename: "fair zone - abbassiya", fromstationid: 56, tostationid: 57 },
    { routename: "abbassiya - fair zone", fromstationid: 57, tostationid: 56 },
    { routename: "abbassiya - abdou pasha", fromstationid: 57, tostationid: 58 },
    { routename: "abdou pasha - abbassiya", fromstationid: 58, tostationid: 57 },
    { routename: "abdou pasha - el-geish", fromstationid: 58, tostationid: 59 },
    { routename: "el-geish - abdou pasha", fromstationid: 59, tostationid: 58 },
    { routename: "el-geish - bab el shaariya", fromstationid: 59, tostationid: 60 },
    { routename: "bab el shaariya - elgeish", fromstationid: 60, tostationid: 59 },
    { routename: "bab el shaariya - attaba", fromstationid: 60, tostationid: 61 },
    { routename: "attaba - bab el shaariya", fromstationid: 61, tostationid: 60 },
    { routename: "attaba - nasser ", fromstationid: 61, tostationid: 20 },
    { routename: "nasser - attaba", fromstationid: 20, tostationid: 61 },
    { routename: "attaba - al-shohadaa ", fromstationid: 61, tostationid: 22 },
    { routename: "al-shohadaa - attaba", fromstationid: 22, tostationid: 61 },
    { routename: "nasser - orabi", fromstationid: 20, tostationid: 21 },
    { routename: "orabi - nasser", fromstationid: 21, tostationid: 20 },
    { routename: "orabi - al-shohadaa", fromstationid: 21, tostationid: 22 },
    { routename: "al-shohadaa - orabi", fromstationid: 22, tostationid: 21 },
    { routename: "nasser - maspero", fromstationid: 20, tostationid: 62 },
    { routename: "maspero - nasser", fromstationid: 62, tostationid: 20 },
    { routename: "maspero - safaa hijazy", fromstationid: 62, tostationid: 63 },
    { routename: "safaa hijazy - maspero", fromstationid: 63, tostationid: 62},
    { routename: "safaa hijazy -kitkat", fromstationid: 63, tostationid: 64},
    { routename: "kitkat - safaa hijazy", fromstationid: 64, tostationid: 63 },
    { routename: "kitkat - sudan", fromstationid: 64, tostationid: 65},
    { routename: "sudan - kitkat", fromstationid: 65, tostationid: 64 },
    { routename: "sudan - imbaba ", fromstationid: 65, tostationid: 66},
    { routename: "imbaba - sudan", fromstationid: 66, tostationid: 65 },
    { routename: "imbaba - el bohy", fromstationid: 66, tostationid: 67 },
    { routename: "el bohy - imbaba", fromstationid: 67, tostationid: 66},
    { routename: "el bohy - el qawmia", fromstationid: 67, tostationid: 68 },
    { routename: "el qawmia - el bohy", fromstationid: 68, tostationid: 67 },
    { routename: "al qawmia - ring road", fromstationid: 68, tostationid: 69 },
    { routename: "ring road - al qawmia", fromstationid: 69, tostationid: 68 },
    { routename: "ring road - road el farag", fromstationid: 69, tostationid: 70 },
    { routename: "road el farag - ring road", fromstationid: 70, tostationid: 60},
    { routename: "kitkat - tawfikia ", fromstationid: 64, tostationid: 71},
    { routename: "tawfikia - kitkat", fromstationid: 71, tostationid: 64},
    { routename: "tawfikia - wadi el nile", fromstationid: 71, tostationid: 72 },
    { routename: "wadi el nile - tawfikia", fromstationid: 72, tostationid: 71},
    { routename: "wadi el nile - gamet el dowel", fromstationid: 72, tostationid: 73 },
    { routename: "gamet el dowel - wadi el nile", fromstationid: 73, tostationid: 72},
    { routename: "gamet el  dowel - boulak el dakrour", fromstationid: 73, tostationid: 74 },
    { routename: "boulak el dakrour - gamet el dowel", fromstationid: 74, tostationid: 73 },
    { routename: "boulak el dakrour - cairo university", fromstationid: 74, tostationid: 75 },
    { routename: "cairo university - boulak el dakrour", fromstationid: 75, tostationid: 74 },
    { routename: "cairo university - faisal", fromstationid: 75, tostationid: 76 },
    { routename: "faisal - cairo university ", fromstationid: 76, tostationid: 75 },
    { routename: "faisal - giza", fromstationid: 76, tostationid: 77 },
    { routename: "giza - faisal", fromstationid: 77, tostationid: 76 },
    { routename: "giza - omm el masryeen", fromstationid: 77, tostationid: 78},
    { routename: "omm el masryeen - giza", fromstationid: 78, tostationid: 77 },
    { routename: "omm el masryeen - sakiat mekky", fromstationid: 78, tostationid: 79 },
    { routename: "sakiat mekky - omm el masryeen", fromstationid: 79, tostationid: 78 },
    { routename: "sakiat mekky - el monib", fromstationid: 79, tostationid: 80 },
    { routename: "el monib - sakiat mekky", fromstationid: 80, tostationid: 79 },
    { routename: "cairo university - el bohth", fromstationid: 75, tostationid: 81 },
    { routename: "el bohth - cairo university", fromstationid: 81, tostationid: 75},
    { routename: "el bohth - dokki", fromstationid: 81, tostationid: 82},
    { routename: "dokki - el bohth", fromstationid: 82, tostationid: 81 },
    { routename: "dokki - opera", fromstationid: 82, tostationid: 83 },
    { routename: "opera - dokki", fromstationid: 83, tostationid: 82 },
    { routename: "al-shohadaa - ghamra", fromstationid: 22, tostationid: 23 },
    { routename: "ghamra - al-shohadaa", fromstationid: 23, tostationid: 22 },
    { routename: "ghamra - el demerdash", fromstationid: 23, tostationid: 24 },
    { routename: "el demerdash - ghamra", fromstationid: 24, tostationid: 23},
    { routename: "el demerdash - manshiet el sadr", fromstationid: 24, tostationid: 25 },
    { routename: "manshiet el sadr - el demerdash", fromstationid: 25, tostationid: 24 },
    { routename: "manshiet el sadr - kobri el qobba", fromstationid: 25, tostationid: 26 },
    { routename: "kobri el qobba - manshiet el sadr", fromstationid: 26, tostationid: 25 },
    { routename: "kobri el qobba - hammamat el qobba ", fromstationid: 26, tostationid: 27 },
    { routename: "hammamt el qobba - kobri el qobba ", fromstationid: 27, tostationid: 26},
    { routename: "hammamt el qobba - saray el qobba", fromstationid: 27, tostationid: 28 },
    { routename: "saray el qobba - hammamt el qobba ", fromstationid: 28, tostationid: 27 },
    { routename: "saray el qobba - hadayeq el zaitoun", fromstationid: 28, tostationid: 29 },
    { routename: "hadayeq el zaitoun - saray el qobba", fromstationid: 29, tostationid: 28},
    { routename: "hadayeq el zaitoun - helmeyet el zaitoun", fromstationid: 29, tostationid: 30 },
    { routename: "helmeyet el zaitoun - hadayeq el zaitoun", fromstationid: 30, tostationid: 29 },
    { routename: "helmeyet el zaitoun - el matareyya ", fromstationid: 30, tostationid: 31 },
    { routename: "el matareyya - helmeyet el zaitoun", fromstationid: 31, tostationid: 30 },
    { routename: "el matareyya - ain shams", fromstationid: 31, tostationid: 32 },
    { routename: "ain shams - el matareyya", fromstationid: 32, tostationid: 31 },
    { routename: "ain shams - ezbet el nakhl", fromstationid: 32, tostationid: 33 },
    { routename: "ezbet el nakhl - ain shams", fromstationid: 33, tostationid: 32 },
    { routename: "ezbet el nakhl - el marg", fromstationid: 33, tostationid: 34 },
    { routename: "el marg - ezbet el nakhl", fromstationid: 34, tostationid: 33 },
    { routename: "el marg - new marg", fromstationid: 34, tostationid: 35 },
    { routename: "new marg - el marg", fromstationid: 35, tostationid: 34 },
    { routename: "helwan - ain helwan", fromstationid: 1, tostationid: 2 },
    { routename: "ain helwan - helwan", fromstationid: 2, tostationid: 1 },
    { routename: "helwan university - ain helwan", fromstationid: 3, tostationid: 2 },
    { routename: "ain helwan - helwan university", fromstationid: 2, tostationid: 3 },
    { routename: "helwan university - wadi hof", fromstationid: 3, tostationid: 4 },
    { routename: "wadi hof - helwan university", fromstationid: 4, tostationid: 3 },
    { routename: "hadayek helwan - wadi hof", fromstationid: 5, tostationid: 4 },
    { routename: "wadi hof - hedayek helwan", fromstationid: 4, tostationid: 5 },
    { routename: "el masraa - hadayek helwan", fromstationid: 6, tostationid: 5 },
    { routename: "hadayek helwan -  el masraa", fromstationid: 5, tostationid: 6 },
    { routename: "el masraa - tura el esmant", fromstationid: 6, tostationid: 7 },
    { routename: "tura el esmant - el masraa", fromstationid: 7, tostationid: 6 },
    { routename: "tura el esmant - kozzika", fromstationid: 7, tostationid: 8 },
    { routename: "kozzika - tura el esmant", fromstationid: 8, tostationid: 7 },
    { routename: "tura el balad - kozzika", fromstationid: 9, tostationid: 8 },
    { routename: "kozzika - tura el balad", fromstationid: 8, tostationid: 9 },
    { routename: "tura el balad - sakanat el maadi ", fromstationid: 9, tostationid: 10 },
    { routename: "sakanat el maadi - tura el balad", fromstationid: 10, tostationid: 9 },
    { routename: "maadi - sakanat el maadi", fromstationid: 11, tostationid: 10 },
    { routename: "sakanat el maadi - maadi", fromstationid: 10, tostationid: 11 },
    { routename: "maadi - hadayek el maadi", fromstationid: 11, tostationid: 12 },
    { routename: "hadayek el maadi - maadi", fromstationid: 12, tostationid: 11 },
    { routename: "hadayek el maadi - dar el salam", fromstationid: 12, tostationid: 13},
    { routename: "dar el salam - hadayek el maadi", fromstationid: 13, tostationid: 12 },
    { routename: "dar el salam - el zahraa", fromstationid: 13, tostationid: 14 },
    { routename: "el zahraa - dar el salam", fromstationid: 14, tostationid: 13 },
    { routename: "el zahraa - mar girgis", fromstationid: 14, tostationid: 15 },
    { routename: "mir girgis - el zahraa", fromstationid: 15, tostationid: 14 },
    { routename: "mir girgis - el malek el saleh", fromstationid: 15, tostationid: 16 },
    { routename: "el malek el saleh - mir girgis", fromstationid: 16, tostationid: 15 },
    { routename: "el malek el saleh - el sayeda zeinab", fromstationid: 16, tostationid: 17 },
    { routename: "el sayeda zeinab - el malek el saleh", fromstationid: 17, tostationid: 16 },
    { routename: "el sayeda zeinab - saad zaghloul", fromstationid: 17, tostationid: 18 },
    { routename: "saad zaghloul - el sayeda zeinab", fromstationid: 18, tostationid: 17 },
    { routename: "saad zaghloul - sadat", fromstationid: 18, tostationid: 19 },
    { routename: "sadat - saad zaghloul", fromstationid: 19, tostationid: 18 },
    { routename: "sadat - opera", fromstationid: 19, tostationid: 83 },
    { routename: "opera - sadat", fromstationid: 83, tostationid: 19 },
    { routename: "sadat - mohamed naguib", fromstationid: 19, tostationid:84  },
    { routename: "mohamed naguib - sadat", fromstationid:84 , tostationid: 19 },
    { routename: "nasser- sadat", fromstationid:20 , tostationid: 19 },
    { routename: "sadat - nasser", fromstationid:19 , tostationid: 20 },
    { routename: "mohamed naguib - attaba", fromstationid:20 , tostationid: 61 },
    { routename: "attaba - mohamed naguib", fromstationid:61 , tostationid: 20 },

    { routename: "el shohadaa - massara", fromstationid:22 , tostationid: 42 },
    { routename: "massara - el shohadaa", fromstationid:42 , tostationid: 22 },
    { routename: "massara - rod el farag", fromstationid:42 , tostationid: 41 },
    { routename: "rod el farag - massara", fromstationid:41 , tostationid: 42 },
    { routename: "rod el farag - st teresa", fromstationid:41 , tostationid: 40 },
    { routename: " st teresa- rod el farag", fromstationid:40 , tostationid: 41 },
    { routename: "st teresa - khalafawy", fromstationid:40 , tostationid: 39 },
    { routename: "khalafawy - st teresa", fromstationid:39 , tostationid: 40 },
    { routename: "khalafawy - mezallat", fromstationid:39 , tostationid: 38 },
    { routename: "mezallat - khalafawy", fromstationid:38 , tostationid: 39 },
    { routename: " mezallat - koliet el zeraa", fromstationid:38 , tostationid: 37 },
    { routename: "koliet el zeraa - mezallat", fromstationid:37 , tostationid: 38 },

    { routename: "koliet el zeraa - shubra el khaimah", fromstationid:37 , tostationid: 36 },
    { routename: "subra el khaimah - koliet el zeraa", fromstationid:36 , tostationid: 37 },
  ];

for (let i = 0; i < routes.length; i++) {
  const element =routes[i];
  await db("se_project.routes").insert(element).returning("*");
}
}


async function uploadS1() {
  let stations = [
    {
      stationname: "Helwan",
      stationtype: "normal",
      stationposition: "start",
      stationstatus: "old",
    },
    {
      stationname: "Ain Helwan",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Helwan university",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Wadi Haf",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Hadayek Helwan",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "El masraa",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Tura El-Esmant",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Kozzika",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Tora El-Balad",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Sakanat El-Maadi",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Maadi",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Hadayek El-Maadi",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Dar El-salam",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },

    {
      stationname: "El-Zahraa",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },

    {
      stationname: "Mar Girgis",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "El-Malek El-Saleh",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Al-Sayeda Zeinab",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, 
     {
      stationname: "Saad Zaghloul",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Sadat",
      stationtype: "transfer",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Nasser",
      stationtype: "transfer",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Orabi",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Al-Shohadaa",
      stationtype: "transfer",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Ghamra",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "El-Demerdash",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Manshiet El-Sadr",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Kobri El-Qobba",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Hammamat El-Qobba",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Saray El-Qobba",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Hadayeq El-Zaitoun",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Helmeyet El-Zaitoun",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "El-Matareyya",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Ain Shams",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Ezbet El-Nakhl",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "El-Marg",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "New Marg",
      stationtype: "normal",
      stationposition: "end",
      stationstatus: "old",
    },
    {
      stationname: "Shubra Al Khaimah",
      stationtype: "normal",
      stationposition: "end",
      stationstatus: "old",
    },
    {
      stationname: "Koliet El-Zeraa",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Mezallat",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Khalafawy",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "St. Teresa",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Rod El-Farag",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Masarra",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Adly Mansour",
      stationtype: "normal",
      stationposition: "start",
      stationstatus: "old",
    },
    {
      stationname: "Haykestep",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Omar Ibn El khattab",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Qubaa",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Hesham Barakat",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "El Nozha",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "El Shams Club",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Alf Maskan",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Helioples",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Haroun",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Al-Ahram",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Koleyet El-Banat",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Stadium",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Fair Zone",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Abbassiya",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Abdou Pasha",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "El-Geish",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Bab El Shaariya",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Attaba",
      stationtype: "transfer",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Maspero",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Safaa Hijazy",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Kit-Kat",
      stationtype: "transfer",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Sudan",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Imbaba",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "El-Bohy",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "El-Qawmia",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Ring Road",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Rod El Farag Corridor",
      stationtype: "normal",
      stationposition: "end",
      stationstatus: "old",
    }, {
      stationname: "Tawfikia",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Wadi El Nile",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Gamet El Dowel",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Boulak El Dakrour",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Cairo University",
      stationtype: "transfer",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Faisal",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Giza",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Omm El-Masryeen",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Sakiat Mekky",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "El Monib",
      stationtype: "normal",
      stationposition: "start",
      stationstatus: "old",
    }, {
      stationname: "El Bohth",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Dokki",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Opera",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Mohamed Naguib",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
  ];
  for (let i = 0; i < stations.length; i++) {
    const element =stations[i];
    await db("se_project.stations").insert(element).returning("*");
  }
}

async function uploadSR1() {

  let SR = [
    { stationid: 43, routeid: 1 },
    { stationid: 43, routeid: 2 },
    { stationid: 44, routeid: 1 },
    { stationid: 44, routeid: 2 },
    { stationid: 44, routeid: 3 },
    { stationid: 45, routeid: 3 },
    { stationid: 44, routeid: 4 },
    { stationid: 45, routeid: 4 },
    { stationid: 45, routeid: 5 },
    { stationid: 46, routeid: 5 },
    { stationid: 46, routeid: 6 },
    { stationid: 45, routeid: 6},
    { stationid: 46, routeid: 7 },
    { stationid: 47, routeid: 7 },
    { stationid: 47, routeid: 8},
    { stationid: 46, routeid: 8},
    { stationid: 47, routeid: 9},
    { stationid: 48, routeid: 9},
    { stationid: 48, routeid: 10},
    { stationid: 47, routeid: 10},
    { stationid: 48, routeid: 11},
    { stationid: 49, routeid: 11},
    { stationid: 49, routeid: 12},
    { stationid: 48, routeid: 12},
    { stationid: 49, routeid: 13},
    { stationid: 50, routeid: 13},
    { stationid: 50, routeid: 14},
    { stationid: 49, routeid: 14},
    { stationid: 50, routeid: 15},
    { stationid: 51, routeid: 15},
    { stationid: 51, routeid: 16},
    { stationid: 50, routeid: 16},
    { stationid: 51, routeid: 17},
    { stationid: 52, routeid: 17},
    { stationid: 52, routeid: 18},
    { stationid: 51, routeid: 18},
    { stationid: 52, routeid: 19},
    { stationid: 53, routeid: 19},
    { stationid: 53, routeid: 20},
    { stationid: 52, routeid: 20},
    { stationid: 53, routeid: 21 },
    { stationid: 54, routeid: 21},
    { stationid: 54, routeid: 22 },
    { stationid: 53, routeid: 22},
    { stationid: 54, routeid: 23},
    { stationid: 55, routeid: 23},
    { stationid: 55, routeid: 24},
    { stationid: 54, routeid: 24 },
    { stationid: 55, routeid: 25},
    { stationid: 56, routeid: 25},
    { stationid: 56, routeid: 26},
    { stationid: 55, routeid: 26},
    { stationid: 57, routeid: 27},
    { stationid: 56, routeid: 27},
    { stationid: 57, routeid: 28},
    { stationid: 56, routeid: 28},
    { stationid: 58, routeid: 29},
    { stationid: 57, routeid: 29},
    { stationid: 58, routeid: 30},
    { stationid: 57, routeid: 30},
    { stationid: 59, routeid: 31},
    { stationid: 58, routeid: 31},
    { stationid: 59, routeid: 32},
    { stationid: 58, routeid: 32},
    { stationid: 60, routeid: 33},
    { stationid: 59, routeid: 33},
    { stationid: 60, routeid: 34},
    { stationid: 59, routeid: 34},
    { stationid: 61, routeid: 35},
    { stationid: 60, routeid: 35},
    { stationid: 61, routeid: 36},
    { stationid: 60, routeid: 36},
    { stationid: 20, routeid: 37},
    { stationid: 61, routeid: 37},
    { stationid: 61, routeid: 38},
    { stationid: 20, routeid: 38},
    { stationid: 22, routeid: 39},
    { stationid: 61, routeid: 39},
    { stationid: 22, routeid: 40},
    { stationid: 61, routeid: 40},
    { stationid: 21, routeid: 41},
    { stationid: 20, routeid: 41},
    { stationid: 21, routeid: 42},
    { stationid: 20, routeid: 42},
    { stationid: 22, routeid: 43},
    { stationid: 21, routeid: 43},
    { stationid: 21, routeid: 44},
    { stationid: 22, routeid: 44},
    { stationid: 62, routeid: 45},
    { stationid: 20, routeid: 45},
    { stationid: 62, routeid: 46},
    { stationid: 20, routeid: 46},
    { stationid: 63, routeid: 47},
    { stationid: 62, routeid: 47},
    { stationid: 63, routeid: 48},
    { stationid: 62, routeid: 48},
    { stationid: 64, routeid: 49},
    { stationid: 63, routeid: 49},
    { stationid: 64, routeid: 50},
    { stationid: 63, routeid: 50},
    { stationid: 65, routeid: 51},
    { stationid: 64, routeid: 51},
    { stationid: 65, routeid: 52},
    { stationid: 64, routeid: 52},
    { stationid: 65, routeid: 53},
    { stationid: 66, routeid: 53},
    { stationid: 66, routeid: 54},
    { stationid: 65, routeid: 54},
    { stationid: 66, routeid: 55},
    { stationid: 67, routeid: 55},
    { stationid: 67, routeid: 56},
    { stationid: 66, routeid: 56},
    { stationid: 67, routeid: 57},
    { stationid: 68, routeid: 57},
    { stationid: 68, routeid: 58},
    { stationid: 67, routeid: 58},
    { stationid: 68, routeid: 59},
    { stationid: 69, routeid: 59},
    { stationid: 69, routeid: 60},
    { stationid: 68, routeid: 60},
    { stationid: 69, routeid: 61},
    { stationid: 70, routeid: 61},
    { stationid: 70, routeid: 62},
    { stationid: 60, routeid: 62},
    { stationid: 64, routeid: 63},
    { stationid: 71, routeid: 63},
    { stationid: 71, routeid: 64},
    { stationid: 64, routeid: 64},
    { stationid: 71, routeid: 65},
    { stationid: 72, routeid: 65},
    { stationid: 72, routeid: 66},
    { stationid: 71, routeid: 66},
    { stationid: 72, routeid: 67},
    { stationid: 73, routeid: 67},
    { stationid: 73, routeid: 68},
    { stationid: 72, routeid: 68},
    { stationid: 73, routeid: 69},
    { stationid: 74, routeid: 69},
    { stationid: 74, routeid: 70},
    { stationid: 73, routeid: 70},
    { stationid: 74, routeid: 71},
    { stationid: 75, routeid: 71},
    { stationid: 75, routeid: 72},
    { stationid: 74, routeid: 72},
    { stationid: 75, routeid: 73},
    { stationid: 76, routeid: 73},
    { stationid: 76, routeid: 74},
    { stationid: 75, routeid: 74},
    { stationid: 76, routeid: 75},
    { stationid: 77, routeid: 75},
    { stationid: 77, routeid: 76},
    { stationid: 76, routeid: 76},
    { stationid: 77, routeid: 77},
    { stationid: 78, routeid: 77},
    { stationid: 78, routeid: 78},
    { stationid: 77, routeid: 78},
    { stationid: 78, routeid: 79},
    { stationid: 79, routeid: 79},
    { stationid: 79, routeid: 80},
    { stationid: 78, routeid: 80},
    { stationid: 79, routeid: 81},
    { stationid: 80, routeid: 81},
    { stationid: 80, routeid: 82},
    { stationid: 79, routeid: 82},
    { stationid: 75, routeid: 83},
    { stationid: 81, routeid: 83},
    { stationid: 81, routeid: 84},
    { stationid: 75, routeid: 84},
    { stationid: 81, routeid: 85},
    { stationid: 82, routeid: 85},
    { stationid: 82, routeid: 86},
    { stationid: 81, routeid: 86},
    { stationid: 82, routeid: 87},
    { stationid: 83, routeid: 87},
    { stationid: 83, routeid: 88},
    { stationid: 82, routeid: 88},
    { stationid: 22, routeid: 89},
    { stationid: 23, routeid: 89},
    { stationid: 23, routeid: 90},
    { stationid: 22, routeid: 90},
    { stationid: 23, routeid: 91},
    { stationid: 24, routeid: 91},
    { stationid: 24, routeid: 92},
    { stationid: 23, routeid: 92},
    { stationid: 24, routeid: 92},
    { stationid: 24, routeid: 93},
    { stationid: 25, routeid: 93},
    { stationid: 24, routeid: 94},
    { stationid: 25, routeid: 94},
    { stationid: 25, routeid: 95},
    { stationid: 26, routeid: 95},
    { stationid: 26, routeid: 96},
    { stationid: 25, routeid: 96},
    { stationid: 26, routeid: 97},
    { stationid: 27, routeid: 97},
    { stationid: 27, routeid: 98},
    { stationid: 26, routeid: 98},
    { stationid: 27, routeid: 99},
    { stationid: 28, routeid: 99},
    { stationid: 28, routeid: 100},
    { stationid: 27, routeid: 100},
    { stationid: 28, routeid: 101},
    { stationid: 29, routeid: 101},
    { stationid: 29, routeid: 102},
    { stationid: 28, routeid: 102},
    { stationid: 29, routeid: 103},
    { stationid: 30, routeid: 103},
    { stationid: 30, routeid: 104},
    { stationid: 29, routeid: 104},
    { stationid: 30, routeid: 10},
    { stationid: 31, routeid: 105},
    { stationid: 37, routeid: 172 },
    { stationid: 36, routeid: 172 },
    { stationid: 37, routeid: 171 },
    { stationid: 36, routeid: 171 },
    { stationid: 37, routeid: 170 },
    { stationid: 38, routeid: 170 },
    { stationid: 37, routeid: 169 },
    { stationid: 38, routeid: 169 },
    { stationid: 38, routeid: 168 },
    { stationid: 39, routeid: 168 },
    { stationid: 38, routeid: 167 },
    { stationid: 39, routeid: 167 },
    { stationid: 39, routeid: 166 },
    { stationid: 40, routeid: 166 },
    { stationid: 40, routeid: 165 },
    { stationid: 39, routeid: 165 },
    { stationid: 40, routeid: 164 },
    { stationid: 41, routeid: 164 },
    { stationid: 40, routeid: 163 },
    { stationid: 41, routeid: 163 },
    { stationid: 42, routeid: 162 },
    { stationid: 41, routeid: 162 },
    { stationid: 42, routeid: 161 },
    { stationid: 41, routeid: 161 },
    { stationid: 42, routeid: 160 },
    { stationid: 22, routeid: 160 },
    { stationid: 42, routeid: 159 },
    { stationid: 22, routeid: 159 },
    { stationid: 61, routeid: 158 },
    { stationid: 20, routeid: 158 },
    { stationid: 61, routeid: 157 },
    { stationid: 20, routeid: 157 },
    { stationid: 20, routeid: 156 },
    { stationid: 19, routeid: 156 },
    { stationid: 20, routeid: 155 },
    { stationid: 19, routeid: 155 },
    { stationid: 84, routeid: 154 },
    { stationid: 19, routeid: 154 },
    { stationid: 84, routeid: 153 },
    { stationid: 19, routeid: 153 },
    { stationid: 83, routeid: 152 }, 
    { stationid: 19, routeid: 152 },
    { stationid: 83, routeid: 151 },
    { stationid: 19, routeid: 151 },
    { stationid: 19, routeid: 150 },
    { stationid: 18, routeid: 150 },
    { stationid: 18, routeid: 149 },
    { stationid: 19, routeid: 149 },
    { stationid: 18, routeid: 148 },
    { stationid: 17, routeid: 148 },
    { stationid: 18, routeid: 147 },
    { stationid: 17, routeid: 147 },
    { stationid: 17, routeid: 146 },
    { stationid: 16, routeid: 146 },
    { stationid: 17, routeid: 145 },
    { stationid: 16, routeid: 145 },
    { stationid: 16, routeid: 144 },
    { stationid: 15, routeid: 144 },
    { stationid: 16, routeid: 143 },
    { stationid: 15, routeid: 143 },
    { stationid: 15, routeid: 142 },
    { stationid: 14, routeid: 142 },
    { stationid: 15, routeid: 141 },
    { stationid: 14, routeid: 141 },
    { stationid: 14, routeid: 140 },
    { stationid: 13, routeid: 140 },
    { stationid: 14, routeid: 139 },
    { stationid: 13, routeid: 139 },
    { stationid: 12, routeid: 138 },
    { stationid: 13, routeid: 138 },
    { stationid: 12, routeid: 137 },
    { stationid: 13, routeid: 137 },
    { stationid: 12, routeid: 136 },
    { stationid: 11, routeid: 136 },
    { stationid: 12, routeid: 135 },
    { stationid: 11, routeid: 135 },
    { stationid: 11, routeid: 134 },
    { stationid: 10, routeid: 134 },
    { stationid: 11, routeid: 133 },
    { stationid: 10, routeid: 133 },
    { stationid: 10, routeid: 132 },
    { stationid: 9, routeid: 132 },
    { stationid: 10, routeid: 131 },
    { stationid: 9, routeid: 131 },
    { stationid: 8, routeid: 130 },
    { stationid: 9, routeid: 130 },
    { stationid: 8, routeid: 129 },
    { stationid: 9, routeid: 129 },
    { stationid:  8, routeid: 128 },
    { stationid: 7, routeid: 128 },
    { stationid: 7, routeid: 127 },
    { stationid: 8, routeid: 127 },
    { stationid: 7, routeid: 126 },
    { stationid: 6, routeid: 126 },
    { stationid: 7, routeid: 125 },
    { stationid: 6, routeid: 125 },
    { stationid: 6, routeid: 124 },
    { stationid: 5, routeid: 124 },
    { stationid: 6, routeid: 123 },
    { stationid: 5, routeid: 123 },
    { stationid: 5, routeid: 122 },
    { stationid: 4, routeid: 122 },
    { stationid: 5, routeid: 121 },
    { stationid: 4, routeid: 121 },
    { stationid: 4, routeid: 120 },
    { stationid: 3, routeid: 120 },
    { stationid: 4, routeid: 119 },
    { stationid: 3, routeid: 119 },
    { stationid: 2, routeid: 118 },
    { stationid: 3, routeid: 118 },
    { stationid: 2, routeid: 117 },
    { stationid: 3, routeid: 117 },
    { stationid: 2, routeid: 116 },
    { stationid: 1, routeid: 116 },
    { stationid: 2, routeid: 115 },
    { stationid: 1, routeid: 115 },
    { stationid: 35, routeid: 114 },
    { stationid: 34, routeid: 114 },
    { stationid: 35, routeid: 113 },
    { stationid: 34, routeid: 113 },
    { stationid: 34, routeid: 112 },
    { stationid: 33, routeid: 112 },
    { stationid: 33, routeid: 111 },
    { stationid: 34, routeid: 111 },
    { stationid: 33, routeid: 110 },
    { stationid: 32, routeid: 110 },
    { stationid: 33, routeid: 109 },
    { stationid: 32, routeid: 109 },
    { stationid: 32, routeid: 108 },
    { stationid: 31, routeid: 108 },
    { stationid: 32, routeid: 107 },
    { stationid: 31, routeid: 107 },
    { stationid: 30, routeid: 106 },
    { stationid: 31, routeid: 106 },

  ];
  for (let i = 0; i < SR.length; i++) {
    const element =SR[i];
    await db("se_project.stationroutes").insert(element).returning("*");
  }

}

async function uploadS2() {
  let stations = [
    {
      stationname: "Helwan",
      stationtype: "normal",
      stationposition: "start",
      stationstatus: "old",
    },
    {
      stationname: "Ain Helwan",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Helwan university",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Wadi Haf",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Hadayek Helwan",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "El masraa",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Tura El-Esmant",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Kozzika",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Tora El-Balad",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Sakanat El-Maadi",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Maadi",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Hadayek El-Maadi",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Dar El-salam",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },

    {
      stationname: "El-Zahraa",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },

    {
      stationname: "Mar Girgis",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "El-Malek El-Saleh",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Al-Sayeda Zeinab",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, 
     {
      stationname: "Saad Zaghloul",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Sadat",
      stationtype: "transfer",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Nasser",
      stationtype: "transfer",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Orabi",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Al-Shohadaa",
      stationtype: "transfer",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Ghamra",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "El-Demerdash",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Manshiet El-Sadr",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Kobri El-Qobba",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Hammamat El-Qobba",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Saray El-Qobba",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Hadayeq El-Zaitoun",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Helmeyet El-Zaitoun",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "El-Matareyya",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Ain Shams",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Ezbet El-Nakhl",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "El-Marg",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "New Marg",
      stationtype: "normal",
      stationposition: "end",
      stationstatus: "old",
    },
    {
      stationname: "Shubra Al Khaimah",
      stationtype: "normal",
      stationposition: "end",
      stationstatus: "old",
    },
    {
      stationname: "Koliet El-Zeraa",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Mezallat",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Khalafawy",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "St. Teresa",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Rod El-Farag",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Masarra",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Adly Mansour",
      stationtype: "normal",
      stationposition: "start",
      stationstatus: "old",
    },
    {
      stationname: "Haykestep",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Omar Ibn El khattab",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Qubaa",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Hesham Barakat",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "El Nozha",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "El Shams Club",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Alf Maskan",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Helioples",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Haroun",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Al-Ahram",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Koleyet El-Banat",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Stadium",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Fair Zone",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Abbassiya",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Abdou Pasha",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "El-Geish",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Bab El Shaariya",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Attaba",
      stationtype: "transfer",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Maspero",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
    {
      stationname: "Safaa Hijazy",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Kit-Kat",
      stationtype: "normal",
      stationposition: "end",
      stationstatus: "old",
    },{
      stationname: "Cairo University",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Faisal",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Giza",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Omm El-Masryeen",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Sakiat Mekky",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "El Monib",
      stationtype: "normal",
      stationposition: "start",
      stationstatus: "old",
    }, {
      stationname: "El Bohth",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Dokki",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Opera",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    }, {
      stationname: "Mohamed Naguib",
      stationtype: "normal",
      stationposition: "middle",
      stationstatus: "old",
    },
  ];
  for (let i = 0; i < stations.length; i++) {
    const element =stations[i];
    await db("se_project.stations").insert(element).returning("*");
  }
}

async function uploadR2() {
  let routes = [
    { routename: "adly mansour - haykestep", fromstationid: 43, tostationid: 44 },
    { routename: "haykestep - adly mansour", fromstationid: 44, tostationid: 43 },
    { routename: "haykestep - omar ibn el khattab", fromstationid: 44, tostationid: 45 },
    { routename: "omar ibn el khattab - haykestep", fromstationid: 45, tostationid: 44},
    { routename: "omar ibn el khattab - qubaa", fromstationid: 45, tostationid: 46 },
    { routename: "qubaa - omar ibn el khattab", fromstationid: 46, tostationid: 45 },
    { routename: "qubaa - hesham barakat", fromstationid: 46, tostationid: 47 },
    { routename: "hesham barakat - qubaa", fromstationid: 47, tostationid: 46 },
    { routename: "hesham barakat - el nozha", fromstationid: 47, tostationid: 48},
    { routename: "el nozha - hesham barakat", fromstationid: 48, tostationid: 47},
    { routename: "el nozha - el shams club", fromstationid: 48, tostationid: 49},
    { routename: "el shams club - el nozha", fromstationid: 49, tostationid: 48},
    { routename: "el shams club - alf maskan", fromstationid: 49, tostationid: 50 },
    { routename: "alf maskan - el shams club", fromstationid: 50, tostationid: 49 },
    { routename: "alf maskan - helioples", fromstationid: 50, tostationid: 51 },
    { routename: "helioples - alf maskan", fromstationid: 51, tostationid: 50 },
    { routename: "helioples - haroun", fromstationid: 51, tostationid: 52 },
    { routename: "haroun - helioples", fromstationid: 52, tostationid: 51 },
    { routename: "haroun - al-ahram", fromstationid: 52, tostationid: 53 },
    { routename: "al-ahram - haroun", fromstationid: 53, tostationid: 52 },
    { routename: "al-ahram - koleyet el-banat", fromstationid: 53, tostationid: 54 },
    { routename: "koleyet el-banat - al-ahram", fromstationid: 54, tostationid: 53 },
    { routename: "koleyet el-banat - stadium", fromstationid: 54, tostationid: 55},
    { routename: "stadium - koleyet el-banat", fromstationid: 55, tostationid: 54 },
    { routename: "stadium - fair zone", fromstationid: 55, tostationid: 56 },
    { routename: "fair zone - stadium", fromstationid: 56, tostationid: 55 },
    { routename: "fair zone - abbassiya", fromstationid: 56, tostationid: 57 },
    { routename: "abbassiya - fair zone", fromstationid: 57, tostationid: 56 },
    { routename: "abbassiya - abdou pasha", fromstationid: 57, tostationid: 58 },
    { routename: "abdou pasha - abbassiya", fromstationid: 58, tostationid: 57 },
    { routename: "abdou pasha - el-geish", fromstationid: 58, tostationid: 59 },
    { routename: "el-geish - abdou pasha", fromstationid: 59, tostationid: 58 },
    { routename: "el-geish - bab el shaariya", fromstationid: 59, tostationid: 60 },
    { routename: "bab el shaariya - elgeish", fromstationid: 60, tostationid: 59 },
    { routename: "bab el shaariya - attaba", fromstationid: 60, tostationid: 61 },
    { routename: "attaba - bab el shaariya", fromstationid: 61, tostationid: 60 },
    { routename: "attaba - nasser ", fromstationid: 61, tostationid: 20 },
    { routename: "nasser - attaba", fromstationid: 20, tostationid: 61 },
    { routename: "attaba - al-shohadaa ", fromstationid: 61, tostationid: 22 },
    { routename: "al-shohadaa - attaba", fromstationid: 22, tostationid: 61 },
    { routename: "nasser - orabi", fromstationid: 20, tostationid: 21 },
    { routename: "orabi - nasser", fromstationid: 21, tostationid: 20 },
    { routename: "orabi - al-shohadaa", fromstationid: 21, tostationid: 22 },
    { routename: "al-shohadaa - orabi", fromstationid: 22, tostationid: 21 },
    { routename: "nasser - maspero", fromstationid: 20, tostationid: 62 },
    { routename: "maspero - nasser", fromstationid: 62, tostationid: 20 },
    { routename: "maspero - safaa hijazy", fromstationid: 62, tostationid: 63 },
    { routename: "safaa hijazy - maspero", fromstationid: 63, tostationid: 62},
    { routename: "safaa hijazy -kitkat", fromstationid: 63, tostationid: 64},
    { routename: "kitkat - safaa hijazy", fromstationid: 64, tostationid: 63 },
    { routename: "cairo university - faisal", fromstationid: 65, tostationid: 66 },
    { routename: "faisal - cairo university ", fromstationid: 66, tostationid: 65 },
    { routename: "faisal - giza", fromstationid: 66, tostationid: 67 },
    { routename: "giza - faisal", fromstationid: 67, tostationid: 66 },
    { routename: "giza - omm el masryeen", fromstationid: 67, tostationid: 68},
    { routename: "omm el masryeen - giza", fromstationid: 68, tostationid: 67 },
    { routename: "omm el masryeen - sakiat mekky", fromstationid: 68, tostationid: 69 },
    { routename: "sakiat mekky - omm el masryeen", fromstationid: 69, tostationid: 68 },
    { routename: "sakiat mekky - el monib", fromstationid: 69, tostationid: 70 },
    { routename: "el monib - sakiat mekky", fromstationid: 70, tostationid: 69 },
    { routename: "cairo university - el bohth", fromstationid: 65, tostationid: 71 },
    { routename: "el bohth - cairo university", fromstationid: 71, tostationid: 65},
    { routename: "el bohth - dokki", fromstationid: 71, tostationid: 72},
    { routename: "dokki - el bohth", fromstationid: 72, tostationid: 71 },
    { routename: "dokki - opera", fromstationid: 72, tostationid: 73 },
    { routename: "opera - dokki", fromstationid: 73, tostationid: 72 },
    { routename: "al-shohadaa - ghamra", fromstationid: 22, tostationid: 23 },
    { routename: "ghamra - al-shohadaa", fromstationid: 23, tostationid: 22 },
    { routename: "ghamra - el demerdash", fromstationid: 23, tostationid: 24 },
    { routename: "el demerdash - ghamra", fromstationid: 24, tostationid: 23},
    { routename: "el demerdash - manshiet el sadr", fromstationid: 24, tostationid: 25 },
    { routename: "manshiet el sadr - el demerdash", fromstationid: 25, tostationid: 24 },
    { routename: "manshiet el sadr - kobri el qobba", fromstationid: 25, tostationid: 26 },
    { routename: "kobri el qobba - manshiet el sadr", fromstationid: 26, tostationid: 25 },
    { routename: "kobri el qobba - hammamat el qobba ", fromstationid: 26, tostationid: 27 },
    { routename: "hammamt el qobba - kobri el qobba ", fromstationid: 27, tostationid: 26},
    { routename: "hammamt el qobba - saray el qobba", fromstationid: 27, tostationid: 28 },
    { routename: "saray el qobba - hammamt el qobba ", fromstationid: 28, tostationid: 27 },
    { routename: "saray el qobba - hadayeq el zaitoun", fromstationid: 28, tostationid: 29 },
    { routename: "hadayeq el zaitoun - saray el qobba", fromstationid: 29, tostationid: 28},
    { routename: "hadayeq el zaitoun - helmeyet el zaitoun", fromstationid: 29, tostationid: 30 },
    { routename: "helmeyet el zaitoun - hadayeq el zaitoun", fromstationid: 30, tostationid: 29 },
    { routename: "helmeyet el zaitoun - el matareyya ", fromstationid: 30, tostationid: 31 },
    { routename: "el matareyya - helmeyet el zaitoun", fromstationid: 31, tostationid: 30 },
    { routename: "el matareyya - ain shams", fromstationid: 31, tostationid: 32 },
    { routename: "ain shams - el matareyya", fromstationid: 32, tostationid: 31 },
    { routename: "ain shams - ezbet el nakhl", fromstationid: 32, tostationid: 33 },
    { routename: "ezbet el nakhl - ain shams", fromstationid: 33, tostationid: 32 },
    { routename: "ezbet el nakhl - el marg", fromstationid: 33, tostationid: 34 },
    { routename: "el marg - ezbet el nakhl", fromstationid: 34, tostationid: 33 },
    { routename: "el marg - new marg", fromstationid: 34, tostationid: 35 },
    { routename: "new marg - el marg", fromstationid: 35, tostationid: 34 },
    { routename: "helwan - ain helwan", fromstationid: 1, tostationid: 2 },
    { routename: "ain helwan - helwan", fromstationid: 2, tostationid: 1 },
    { routename: "helwan university - ain helwan", fromstationid: 3, tostationid: 2 },
    { routename: "ain helwan - helwan university", fromstationid: 2, tostationid: 3 },
    { routename: "helwan university - wadi hof", fromstationid: 3, tostationid: 4 },
    { routename: "wadi hof - helwan university", fromstationid: 4, tostationid: 3 },
    { routename: "hadayek helwan - wadi hof", fromstationid: 5, tostationid: 4 },
    { routename: "wadi hof - hedayek helwan", fromstationid: 4, tostationid: 5 },
    { routename: "el masraa - hadayek helwan", fromstationid: 6, tostationid: 5 },
    { routename: "hadayek helwan -  el masraa", fromstationid: 5, tostationid: 6 },
    { routename: "el masraa - tura el esmant", fromstationid: 6, tostationid: 7 },
    { routename: "tura el esmant - el masraa", fromstationid: 7, tostationid: 6 },
    { routename: "tura el esmant - kozzika", fromstationid: 7, tostationid: 8 },
    { routename: "kozzika - tura el esmant", fromstationid: 8, tostationid: 7 },
    { routename: "tura el balad - kozzika", fromstationid: 9, tostationid: 8 },
    { routename: "kozzika - tura el balad", fromstationid: 8, tostationid: 9 },
    { routename: "tura el balad - sakanat el maadi ", fromstationid: 9, tostationid: 10 },
    { routename: "sakanat el maadi - tura el balad", fromstationid: 10, tostationid: 9 },
    { routename: "maadi - sakanat el maadi", fromstationid: 11, tostationid: 10 },
    { routename: "sakanat el maadi - maadi", fromstationid: 10, tostationid: 11 },
    { routename: "maadi - hadayek el maadi", fromstationid: 11, tostationid: 12 },
    { routename: "hadayek el maadi - maadi", fromstationid: 12, tostationid: 11 },
    { routename: "hadayek el maadi - dar el salam", fromstationid: 12, tostationid: 13},
    { routename: "dar el salam - hadayek el maadi", fromstationid: 13, tostationid: 12 },
    { routename: "dar el salam - el zahraa", fromstationid: 13, tostationid: 14 },
    { routename: "el zahraa - dar el salam", fromstationid: 14, tostationid: 13 },
    { routename: "el zahraa - mar girgis", fromstationid: 14, tostationid: 15 },
    { routename: "mir girgis - el zahraa", fromstationid: 15, tostationid: 14 },
    { routename: "mir girgis - el malek el saleh", fromstationid: 15, tostationid: 16 },
    { routename: "el malek el saleh - mir girgis", fromstationid: 16, tostationid: 15 },
    { routename: "el malek el saleh - el sayeda zeinab", fromstationid: 16, tostationid: 17 },
    { routename: "el sayeda zeinab - el malek el saleh", fromstationid: 17, tostationid: 16 },
    { routename: "el sayeda zeinab - saad zaghloul", fromstationid: 17, tostationid: 18 },
    { routename: "saad zaghloul - el sayeda zeinab", fromstationid: 18, tostationid: 17 },
    { routename: "saad zaghloul - sadat", fromstationid: 18, tostationid: 19 },
    { routename: "sadat - saad zaghloul", fromstationid: 19, tostationid: 18 },
    { routename: "sadat - opera", fromstationid: 19, tostationid: 73 },
    { routename: "opera - sadat", fromstationid: 73, tostationid: 19 },
    { routename: "sadat - mohamed naguib", fromstationid: 19, tostationid:74  },
    { routename: "mohamed naguib - sadat", fromstationid:74 , tostationid: 19 },
    { routename: "nasser- sadat", fromstationid:20 , tostationid: 19 },
    { routename: "sadat - nasser", fromstationid:19 , tostationid: 20 },
    { routename: "mohamed naguib - attaba", fromstationid:74 , tostationid: 61 },
    { routename: "attaba - mohamed naguib", fromstationid:61 , tostationid: 74 },
    { routename: "el shohadaa - massara", fromstationid:22 , tostationid: 42 },
    { routename: "massara - el shohadaa", fromstationid:42 , tostationid: 22 },
    { routename: "massara - rod el farag", fromstationid:42 , tostationid: 41 },
    { routename: "rod el farag - massara", fromstationid:41 , tostationid: 42 },
    { routename: "rod el farag - st teresa", fromstationid:41 , tostationid: 40 },
    { routename: " st teresa- rod el farag", fromstationid:40 , tostationid: 41 },
    { routename: "st teresa - khalafawy", fromstationid:40 , tostationid: 39 },
    { routename: "khalafawy - st teresa", fromstationid:39 , tostationid: 40 },
    { routename: "khalafawy - mezallat", fromstationid:39 , tostationid: 38 },
    { routename: "mezallat - khalafawy", fromstationid:38 , tostationid: 39 },
    { routename: " mezallat - koliet el zeraa", fromstationid:38 , tostationid: 37 },
    { routename: "koliet el zeraa - mezallat", fromstationid:37 , tostationid: 38 },
    { routename: "koliet el zeraa - shubra el khaimah", fromstationid:37 , tostationid: 36 },
    { routename: "subra el khaimah - koliet el zeraa", fromstationid:36 , tostationid: 37 },
  ];

for (let i = 0; i < routes.length; i++) {
  const element =routes[i];
  await db("se_project.routes").insert(element).returning("*");
}
}

async function uploadSR2() {

  let SR = [
    { stationid: 43, routeid: 1 },
    { stationid: 43, routeid: 2 },
    { stationid: 44, routeid: 1 },
    { stationid: 44, routeid: 2 },
    { stationid: 44, routeid: 3 },
    { stationid: 45, routeid: 3 },
    { stationid: 44, routeid: 4 },
    { stationid: 45, routeid: 4 },
    { stationid: 45, routeid: 5 },
    { stationid: 46, routeid: 5 },
    { stationid: 46, routeid: 6 },
    { stationid: 45, routeid: 6},
    { stationid: 46, routeid: 7 },
    { stationid: 47, routeid: 7 },
    { stationid: 47, routeid: 8},
    { stationid: 46, routeid: 8},
    { stationid: 47, routeid: 9},
    { stationid: 48, routeid: 9},
    { stationid: 48, routeid: 10},
    { stationid: 47, routeid: 10},
    { stationid: 48, routeid: 11},
    { stationid: 49, routeid: 11},
    { stationid: 49, routeid: 12},
    { stationid: 48, routeid: 12},
    { stationid: 49, routeid: 13},
    { stationid: 50, routeid: 13},
    { stationid: 50, routeid: 14},
    { stationid: 49, routeid: 14},
    { stationid: 50, routeid: 15},
    { stationid: 51, routeid: 15},
    { stationid: 51, routeid: 16},
    { stationid: 50, routeid: 16},
    { stationid: 51, routeid: 17},
    { stationid: 52, routeid: 17},
    { stationid: 52, routeid: 18},
    { stationid: 51, routeid: 18},
    { stationid: 52, routeid: 19},
    { stationid: 53, routeid: 19},
    { stationid: 53, routeid: 20},
    { stationid: 52, routeid: 20},
    { stationid: 53, routeid: 21 },
    { stationid: 54, routeid: 21},
    { stationid: 54, routeid: 22 },
    { stationid: 53, routeid: 22},
    { stationid: 54, routeid: 23},
    { stationid: 55, routeid: 23},
    { stationid: 55, routeid: 24},
    { stationid: 54, routeid: 24 },
    { stationid: 55, routeid: 25},
    { stationid: 56, routeid: 25},
    { stationid: 56, routeid: 26},
    { stationid: 55, routeid: 26},
    { stationid: 57, routeid: 27},
    { stationid: 56, routeid: 27},
    { stationid: 57, routeid: 28},
    { stationid: 56, routeid: 28},
    { stationid: 58, routeid: 29},
    { stationid: 57, routeid: 29},
    { stationid: 58, routeid: 30},
    { stationid: 57, routeid: 30},
    { stationid: 59, routeid: 31},
    { stationid: 58, routeid: 31},
    { stationid: 59, routeid: 32},
    { stationid: 58, routeid: 32},
    { stationid: 60, routeid: 33},
    { stationid: 59, routeid: 33},
    { stationid: 60, routeid: 34},
    { stationid: 59, routeid: 34},
    { stationid: 61, routeid: 35},
    { stationid: 60, routeid: 35},
    { stationid: 61, routeid: 36},
    { stationid: 60, routeid: 36},
    { stationid: 20, routeid: 37},
    { stationid: 61, routeid: 37},
    { stationid: 61, routeid: 38},
    { stationid: 20, routeid: 38},
    { stationid: 22, routeid: 39},
    { stationid: 61, routeid: 39},
    { stationid: 22, routeid: 40},
    { stationid: 61, routeid: 40},
    { stationid: 21, routeid: 41},
    { stationid: 20, routeid: 41},
    { stationid: 21, routeid: 42},
    { stationid: 20, routeid: 42},
    { stationid: 22, routeid: 43},
    { stationid: 21, routeid: 43},
    { stationid: 21, routeid: 44},
    { stationid: 22, routeid: 44},
    { stationid: 62, routeid: 45},
    { stationid: 20, routeid: 45},
    { stationid: 62, routeid: 46},
    { stationid: 20, routeid: 46},
    { stationid: 63, routeid: 47},
    { stationid: 62, routeid: 47},
    { stationid: 63, routeid: 48},
    { stationid: 62, routeid: 48},
    { stationid: 64, routeid: 49},
    { stationid: 63, routeid: 49},
    { stationid: 64, routeid: 50},
    { stationid: 63, routeid: 50},
    { stationid: 65, routeid: 51},
    { stationid: 66, routeid: 51},
    { stationid: 65, routeid: 52},
    { stationid: 66, routeid: 52},
    { stationid: 67, routeid: 53},
    { stationid: 66, routeid: 53},
    { stationid: 66, routeid: 54},
    { stationid: 67, routeid: 54},
    { stationid: 68, routeid: 55},
    { stationid: 67, routeid: 55},
    { stationid: 67, routeid: 56},
    { stationid: 68, routeid: 56},
    { stationid: 69, routeid: 57},
    { stationid: 68, routeid: 57},
    { stationid: 68, routeid: 58},
    { stationid: 69, routeid: 58},
    { stationid: 70, routeid: 59},
    { stationid: 69, routeid: 59},
    { stationid: 69, routeid: 60},
    { stationid: 70, routeid: 60},
    { stationid: 65, routeid: 61},
    { stationid: 71, routeid: 61},
    { stationid: 71, routeid: 62},
    { stationid: 65, routeid: 62},
    { stationid: 61, routeid: 63},
    { stationid: 72, routeid: 63},
    { stationid: 71, routeid: 64},
    { stationid: 72, routeid: 64},
    { stationid: 73, routeid: 65},
    { stationid: 72, routeid: 65},
    { stationid: 72, routeid: 66},
    { stationid: 73, routeid: 66},
    { stationid: 22, routeid: 67},
    { stationid: 23, routeid: 67},
    { stationid: 23, routeid: 68},
    { stationid: 22, routeid: 68},
    { stationid: 23, routeid: 69},
    { stationid: 24, routeid: 69},
    { stationid: 24, routeid: 70},
    { stationid: 23, routeid: 70},
    { stationid: 24, routeid: 71},
    { stationid: 25, routeid: 71},
    { stationid: 25, routeid: 72},
    { stationid: 24, routeid: 72},
    { stationid: 25, routeid: 73},
    { stationid: 26, routeid: 73},
    { stationid: 26, routeid: 74},
    { stationid: 25, routeid: 74},
    { stationid: 26, routeid: 75},
    { stationid: 27, routeid: 75},
    { stationid: 27, routeid: 76},
    { stationid: 26, routeid: 76},
    { stationid: 27, routeid: 77},
    { stationid: 28, routeid: 77},
    { stationid: 28, routeid: 78},
    { stationid: 27, routeid: 78},
    { stationid: 28, routeid: 79},
    { stationid: 29, routeid: 79},
    { stationid: 29, routeid: 80},
    { stationid: 28, routeid: 80},
    { stationid: 29, routeid: 81},
    { stationid: 30, routeid: 81},
    { stationid: 30, routeid: 82},
    { stationid: 29, routeid: 82},
    { stationid: 30, routeid: 83},
    { stationid: 31, routeid: 83},
    { stationid: 31, routeid: 84},
    { stationid: 30, routeid: 84},
    { stationid: 31, routeid: 85},
    { stationid: 32, routeid: 85},
    { stationid: 32, routeid: 86},
    { stationid: 31, routeid: 86},
    { stationid: 32, routeid: 87},
    { stationid: 33, routeid: 87},
    { stationid: 33, routeid: 88},
    { stationid: 32, routeid: 88},
    { stationid: 33, routeid: 89},
    { stationid: 34, routeid: 89},
    { stationid: 33, routeid: 90},
    { stationid: 34, routeid: 90},
    { stationid: 34, routeid: 91},
    { stationid: 35, routeid: 91},
    { stationid: 34, routeid: 92},
    { stationid: 35, routeid: 92},
    { stationid: 1, routeid: 93},
    { stationid: 2, routeid: 93},
    { stationid: 2, routeid: 94},
    { stationid: 1, routeid: 94},
    { stationid: 2, routeid: 95},
    { stationid: 3, routeid: 95},
    { stationid: 2, routeid: 96},
    { stationid: 3, routeid: 96},
    { stationid: 3, routeid: 97},
    { stationid: 4, routeid: 97},
    { stationid: 3, routeid: 98},
    { stationid: 4, routeid: 98},
    { stationid: 4, routeid: 99},
    { stationid: 5, routeid: 99},
    { stationid: 4, routeid: 100},
    { stationid: 5, routeid: 100},
    { stationid: 6, routeid: 101},
    { stationid: 5, routeid: 101},
    { stationid: 6, routeid: 102},
    { stationid: 5, routeid: 102},
    { stationid: 6, routeid: 103},
    { stationid: 7, routeid: 103},
    { stationid: 6, routeid: 104},
    { stationid: 7, routeid: 104},
    { stationid: 7, routeid: 105},
    { stationid: 8, routeid: 105},
    { stationid: 7, routeid: 106},
    { stationid: 8, routeid: 106 },
    { stationid: 37, routeid: 150 },
    { stationid: 36, routeid: 150 },
    { stationid: 37, routeid: 149 },
    { stationid: 36, routeid: 149 },
    { stationid: 37, routeid: 148 },
    { stationid: 38, routeid: 148 },
    { stationid: 37, routeid: 147 },
    { stationid: 38, routeid: 147 },
    { stationid: 38, routeid: 146 },
    { stationid: 39, routeid: 146 },
    { stationid: 38, routeid: 145 },
    { stationid: 39, routeid: 145 },
    { stationid: 39, routeid: 144 },
    { stationid: 40, routeid: 144 },
    { stationid: 39, routeid: 143 },
    { stationid: 40, routeid: 143 },
    { stationid: 41, routeid: 142 },
    { stationid: 40, routeid: 142 },
    { stationid: 41, routeid: 141 },
    { stationid: 40, routeid: 141 },
    { stationid: 41, routeid: 140 },
    { stationid: 42, routeid: 140 },
    { stationid: 41, routeid: 139 },
    { stationid: 42, routeid: 139 },
    { stationid: 22, routeid: 138 },
    { stationid: 42, routeid: 138 },
    { stationid: 22, routeid: 137 },
    { stationid: 42, routeid: 137 },
    { stationid: 74, routeid: 136 },
    { stationid: 61, routeid: 136 },
    { stationid: 74, routeid: 135 },
    { stationid: 61, routeid: 135 },
    { stationid: 19, routeid: 134 },
    { stationid: 20, routeid: 134 },
    { stationid: 19, routeid: 133 },
    { stationid: 20, routeid: 133 },
    { stationid: 74, routeid: 132 },
    { stationid: 19, routeid: 132 },
    { stationid: 74, routeid: 131 },
    { stationid: 19, routeid: 131 },
    { stationid: 73, routeid: 130 },
    { stationid: 19, routeid: 130 },
    { stationid: 73, routeid: 129 },
    { stationid: 19, routeid: 129 },
    { stationid: 18, routeid: 128 },
    { stationid: 19, routeid: 128 },
    { stationid: 19, routeid: 127 },
    { stationid: 18, routeid: 127 },
    { stationid: 17, routeid: 126 },
    { stationid: 18, routeid: 126 },
    { stationid: 17, routeid: 125 },
    { stationid: 18, routeid: 125 },
    { stationid: 16, routeid: 124 },
    { stationid: 17, routeid: 124 },
    { stationid: 16, routeid: 123 },
    { stationid: 17, routeid: 123 },
    { stationid: 15, routeid: 122 },
    { stationid: 16, routeid: 122 },
    { stationid: 16, routeid: 121 },
    { stationid: 15, routeid: 121 },
    { stationid: 14, routeid: 120 },
    { stationid: 15, routeid: 120 },
    { stationid: 15, routeid: 119 },
    { stationid: 14, routeid: 119 },
    { stationid: 14, routeid: 118 },
    { stationid: 13, routeid: 118 },
    { stationid: 14, routeid: 117 },
    { stationid: 13, routeid: 117 },
    { stationid: 13, routeid: 116 },
    { stationid: 12, routeid: 116 },
    { stationid: 13, routeid: 115 },
    { stationid: 12, routeid: 115 },
    { stationid: 12, routeid: 114 },
    { stationid: 11, routeid: 114 },
    { stationid: 12, routeid: 113 },
    { stationid: 11, routeid: 113 },
    { stationid: 11, routeid: 112 },
    { stationid: 10, routeid: 112 },
    { stationid: 11, routeid: 111 },
    { stationid: 10, routeid: 111 },
    { stationid: 10, routeid: 110 },
    { stationid: 9, routeid: 110 },
    { stationid: 10, routeid: 109 },
    { stationid: 9, routeid: 109 },
    { stationid: 8, routeid: 108 },
    { stationid: 9, routeid: 108 },
    { stationid: 8, routeid: 107 },
    { stationid: 9, routeid: 107 },
  ];
  for (let i = 0; i < SR.length; i++) {
    const element =SR[i];
    await db("se_project.stationroutes").insert(element).returning("*");
  }

}

//uploadS2();// first to run
//uploadR2(); //second
uploadSR2(); //third
